# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HalaanTask' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HalaanTask 
  pod 'HalaanTaskEntity', :path => '../HalaanEntities'
  pod 'HalaanTaskPresentation', :path => '../HalaanTaskPresentation'
  pod 'HalaanTaskBussiness', :path => '../HalaanTaskBussiness'

  target 'HalaanTaskTests' do
    inherit! :search_paths
    # Pods for testing
  pod 'HalaanTaskEntity', :path => '../HalaanEntities'
  pod 'HalaanTaskPresentation', :path => '../HalaanTaskPresentation'
  pod 'HalaanTaskBussiness', :path => '../HalaanTaskBussiness'
  end

  target 'HalaanTaskUITests' do
    # Pods for testing
  pod 'HalaanTaskEntity', :path => '../HalaanEntities'
  pod 'HalaanTaskPresentation', :path => '../HalaanTaskPresentation'
  pod 'HalaanTaskBussiness', :path => '../HalaanTaskBussiness'
  end

end
