# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'HalaanTaskBussiness' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'HalaanTaskEntity', :path => '../HalaanEntities'

  # Pods for HalaanTaskBussiness

  target 'HalaanTaskBussinessTests' do
    # Pods for testing
  end

end
