# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'HalaanTaskPR' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'HalaanTaskEntity', :path => '../HalaanEntities'

  # Pods for HalaanTaskPR

  target 'HalaanTaskPRTests' do
    # Pods for testing
  end

end
